@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "john doe",
	"email": "johndoe3@email.com",
    "cpf": "12345678900",
	"password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{ 
    "cpf": "12345678900",
	"password": "123456"
}

###
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}
