@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "john doe",
	"email": "johndoe@email.com",
    "cpf": "12345678900",
	"password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{ 
    "cpf": "12345678900",
	"password": "123456"
}

###
# @name create_order
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
# @name create_recipient
POST {{baseUrl}}/accounts/recipient
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "john doe2",
    "cpf": "12345678901",
	"phone": "7798888-7777",
    "address": "Rua nada Bairro Grande"
}