@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "deliveryman",
	"email": "deliveryman@email.com",
    "cpf": "12345678901",
	"password": "123456"
}

###

# @name fetch_deliveryman
GET  {{baseUrl}}/accounts/deliverymans
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{ 
    "cpf": "12345678900",
	"password": "123456"
}

###

# @name create_recipient
POST {{baseUrl}}/accounts/recipient
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "john doe2",
    "cpf": "12345678901",
	"phone": "7798888-7777",
    "address": "Rua nada Bairro Grande"
}

### 

# @name fetch_recipients
GET  {{baseUrl}}/accounts/recipients
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_order
POST {{baseUrl}}/recipients/20465089-a6c7-4a53-94eb-596a2b053d41/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Create Order 1",
	"latitude": -16.0167985,
    "longitude": -48.0722519
}

###

# @name fetch_recent_orders
GET  {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

